# Generated by Django 2.0.7 on 2023-11-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(choices=[(0, 'Kitchen'), (1, 'Bathroom'), (2, 'Living_room'), (3, 'Bedroom')])),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='request_images/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('unit_number', models.IntegerField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('user_type', models.IntegerField(choices=[(0, 'Tenant'), (1, 'Maintenance'), (2, 'Management')])),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_maintenance.User'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='unit_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_maintenance.Tenant'),
        ),
    ]
