# Generated by Django 2.0.7 on 2023-11-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_maintenance', '0002_auto_20231129_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
