# Generated by Django 2.1.5 on 2023-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_maintenance', '0003_auto_20231129_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='request_images/'),
        ),
    ]
