# Generated by Django 2.1.5 on 2023-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_maintenance', '0004_auto_20231130_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='unit_number',
            field=models.IntegerField(),
        ),
    ]
