# Generated by Django 2.1.5 on 2023-12-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_maintenance', '0006_maintenancerequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='area',
            field=models.IntegerField(choices=[(0, 'Kitchen'), (1, 'Bathroom'), (2, 'Living Room'), (3, 'Bedroom')]),
        ),
    ]
