# Generated by Django 2.1.5 on 2023-12-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_maintenance', '0007_auto_20231201_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='apartment_maintenance.Tenant'),
            preserve_default=False,
        ),
    ]
