# Generated by Django 2.1.5 on 2023-12-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_maintenance', '0008_maintenancerequest_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='tenant',
            new_name='tenant_key',
        ),
    ]
